version: '3.4'
services:
    nexus:
        image: nginx:1.17.8
        ports:
            - 80:80
        volumes:
            - ./nexus/build:/usr/share/nginx/html:ro
            - ./nginx/conf.d:/etc/nginx/conf.d:ro
            - ./nginx/proxy_params:/etc/nginx/proxy_params:ro
            - ./nginx/.htpasswd:/etc/nginx/.htpasswd
    node:
        image: node:13
        user: '1000'
        working_dir: /app
        volumes:
            - ./nexus:/app
    octoprint_dagoma1:
        image: nunofgs/octoprint:1.3.10
        privileged: true
        environment:
            CAMERA_DEV: /dev/cam1
        volumes:
            - ./dagoma1:/data
            - /dev:/dev
    octoprint_dagoma2:
        image: nunofgs/octoprint:1.3.10
        privileged: true
        volumes:
            - ./dagoma2:/data
            - /dev:/dev
    octoprint_alfawise:
        image: nunofgs/octoprint:1.3.10
        environment:
            CAMERA_DEV: /dev/cam2
        privileged: true
        volumes:
            - ./alfawise:/data
            - /dev:/dev

