export const GET_STATUS = '/printers/getStatus'
export const GET_STATUS_SUCCESS = '/printers/getStatusSuccess'
export const GET_STATUS_ERROR = '/printers/getStatusError'
export const SELECT = '/printers/select'
export const REFRESH = '/printers/refresh'
